### ISSUE TITLE
Error following README installation for Django 2.1.2: 'Settings' object has no attribute 'SITE_ID' 

### ISSUE THREAD

**Issue by Ajorona** [HonzaKral/django-threadedcomments#103]
I am getting an error

    'Settings' object has no attribute 'SITE_ID'

How can I correct this? I am following the instructions on the README for setting up the threaded comments app, but when I provide a template that displays the comments for my article, I get that error on a GET request.

**Comment by elcone** [comment]
You need to [enable](https://docs.djangoproject.com/es/2.1/ref/contrib/sites/#enabling-the-sites-framework) the *sites* framework.

1. Add 'django.contrib.sites' to your INSTALLED_APPS in `settings.py`.
2. Also in `settings.py` set `SITE_ID = 1`
3. Run `python manage migrate`

**Comment by Ajorona** [comment]
Thanks I had 'django.contribe.sites' in my INSTALLED_APPS, the missing piece was setting SITE_ID = 1
