### ISSUE TITLE
Migrations fail in MySQL with "FUNCTION demo_dev.TO_CHAR does not exist"

### ISSUE THREAD

**Issue by elfsternberg** [HonzaKral/django-threadedcomments#11]
(This is with MySQL 5.0.71)

TO_CHAR appears to be unavailable in MySQL.  The problem is here:

<pre> (SELECT TO_CHAR(id, '%s')) AS tree_path,
       ''
FROM django_comments;
""" % ''.zfill(PATH_DIGITS)
</pre>

The correct substitution is:

<pre>(SELECT lpad(format(id, 0), %d, '0')) AS tree_path,
       ''
FROM django_comments;
""" % PATH_DIGITS
</pre>

Note that I've removed the zfill, and used a MySQL internal function to do the padding as required.

**Comment by vdboor** [comment]
Is this still an issue on the latest MySQL releases? Note that 5.0 is no longer supported.
