### ISSUE TITLE
tree_path TextField stored as NCLOB in Oracle

### ISSUE THREAD

**Issue by imacleod** [HonzaKral/django-threadedcomments#20]
Oracle unfortunately stores TextFields as NCLOBs, preventing them from being indexed and used in DISTINCT queries. Django documentation discussing this is here:

http://docs.djangoproject.com/en/1.2/ref/databases/#textfield-limitations

This prevents threadedcomments from working correctly in Oracle. Trying to post comments to the database results in the error "ORA-00932: inconsistent datatypes: expected - got NCLOB".

**Comment by vdboor** [comment]
In the newest 1.0b1 release, we've replaced the TextField with a CharField so these issues are now gone!
