### ISSUE TITLE
fill_tree latest first?

### ISSUE THREAD

**Issue by bhaugen** [HonzaKral/django-threadedcomments#36]
Been trying to figure out how to get a comment tree with the root comments order_by('-submit_date').

If I sort the comments first, I get dups of the comments that have children.  

Any ideas?  Tips? Hints?

I'll report back when I got a solution.  Or not...

**Comment by vdboor** [comment]
If anyone can provide a good pull request, I'd be happy to accept it.
I've seen some work in our network (https://github.com/fsboehme/django-threadedcomments/commit/fafde850728a99303c9c5b6c7d5f5b5ee7b8d85f) but someone has to complete that so we can merge it!

**Comment by vdboor** [comment]
There is now a `latest` flag support for the template tags in v1.1
