### ISSUE TITLE
 invalid literal for int() with base 10: - need help finding what is causing the problem

### ISSUE THREAD

**Issue by davemerwin** [HonzaKral/django-threadedcomments#37]
I'm not sure where to trace this too. Any help would be welcome.

Here's the error:

 File "/home/dminlgp/.virtualenvs/dminlgp.com/src/django-threadedcomments/threadedcomments/models.py", line 26, in _root_id
   return int(self.tree_path.split(PATH_SEPARATOR)[0])

ValueError: invalid literal for int() with base 10: ''

**Comment by Sonicmr** [comment]
same problem here, anybody was able to fix it ?

**Comment by traverseda** [comment]
Are you nominating a custom field as a primary key? Threaded-comments uses generic forignkeys, and they all expect integers as your PK.

**Comment by Sonicmr** [comment]
Threaded-comments uses generic forignkeys, and they all expect integers as your PK.

I provide integers as PK

**Comment by traverseda** [comment]
Not the same problem I had. Sorry mate.

**Comment by vdboor** [comment]
If this is still happening, please let me know. I'm closing now for inactivity.

**Comment by vdboor** [comment]
Is this issue still happening? I have a hard time reproducing it. Can someone post example code that causes this?
