### ISSUE TITLE
Jacob Kaplan-Moss: deprecate django.contrib.comments

### ISSUE THREAD

**Issue by emacsway** [HonzaKral/django-threadedcomments#42]
Jacob Kaplan-Moss: "This one's simple: I'd like to deprecate django.contrib.comments,
scheduling it to be removed in a couple of releases." http://groups.google.com/group/django-developers/msg/8cb9cdb049fe721d

"If someone volunteers to maintain it as an external project I'll move
the code to a new repo and direct people there in the docs. If nobody
volunteers, then it'll go to the great /dev/null in the sky."

**Comment by vdboor** [comment]
This is now supported in django-threadedcomments 1.0b1 !
When `django_comments` is added to INSTALLED_APPS, it will be picked up by default.
For Django 1.7 and 1.8 this is required, as the migrations depend on it.
