### ISSUE TITLE
DatabaseError: (1170, "BLOB/TEXT column 'tree_path' used in key specification without a key length")

### ISSUE THREAD

**Issue by schmico** [HonzaKral/django-threadedcomments#48]
We are getting the following error when running south migrations after implementing threadedcomments. I see a much older bug like this logged, and the problem at that time was Django indexing. Has this been resolved since?

**Comment by vdboor** [comment]
This is now fixed in django-threadedcomments 1.0b1. We've replaced the TextField with a CharField, that MySQL can apply indexes at.
