### ISSUE TITLE
Tree template produces broken markup

### ISSUE THREAD

**Issue by eusonic** [HonzaKral/django-threadedcomments#53]
The tree template produces broken markup in some cases.

## Case 1

**Follow these steps:**

1. Post a comment. This is Comment 1
2. Reply to Comment 1. This is Comment 2
3. Reply to Comment 2. This is Comment 3
4. Reply to Comment 1. This is Comment 4

**Here is the tree:**

* Comment 1
  * Comment 2
    * Comment 3
  * Comment 4

**Here is the HTML output (cleaned up):**

```
<ul>
    <li>
        Comment 1
        <ul>
            <li>
                Comment 2
                <ul>
                    <li>
                        Comment 3
                    </li>
                </ul>
            <li>
                Comment 4
            </li>
        </ul>
    </li>
</ul>
```

There is a missing `</li>` before Comment 4. In other words, Comment 2's parent `<li>` is not getting closed.

## Case 2

**Follow these steps:**

1. Post a comment.
2. Post another comment. NOT a reply to the first comment.

**Here is the tree:**

* Comment 1
* Comment 2

**Here is the HTML output (cleaned up):**

```
<ul>
    <li>
        Comment 1
    </li>
</ul>
</li>
<ul>
    <li>
        Comment 2
    </li>
</ul>
```

There is an extra `<\li>` between the two comments.

**Comment by vdboor** [comment]
Thanks for the good explaination, this is now merged!
