### ISSUE TITLE
Using different model

### ISSUE THREAD

**Issue by vinaychandra** [HonzaKral/django-threadedcomments#57]
How can we use a custom model for comments?

For example, the current comments have only a body. What to do if I want include more details to the comments so that some parts of it can also be rendered in the form?

**Comment by vdboor** [comment]
You can pull that off by making an custom comments app, and use that as `COMMENTS_APP = "myapp"` in your settings. Your comments app would have to provide a `get_form()` and `get_model()` function that returns your form and model classes. You can let those inherit from the `ThreadedComments` and `ThreadedCommentsForm` class off course!
