### ISSUE TITLE
Django 1.7 and 1.8 support

### ISSUE THREAD

**Issue by Felix-neko** [HonzaKral/django-threadedcomments#62]
Good evening!

Aren't you going to add  Django 1.7 support?

**Comment by vdboor** [comment]
Yes! In fact, this has just been added to git! If you can confirm this works, we can release that asap!

**Comment by vdboor** [comment]
django-threadedcomments 1.0b1 has just been released on PyPI for Django 1.7 and 1.8 support

**Comment by Felix-neko** [comment]
Спасибо, товарищ!
