### ISSUE TITLE
Django_comments

### ISSUE THREAD

**Issue by Sonicmr** [HonzaKral/django-threadedcomments#64]
Does this work with Django_Comments (not django.contrib.comments) and if yes how?

I am getting the following error
   from django.contrib.comments.models import Comment
ImportError: No module named comments.models

I am using Django 1.8 so I have to use django_comments

**Comment by vdboor** [comment]
The latest beta version does support this. You can use:

`pip install django-threadedcomments==1.0b1`

It checks whether you have `django.contrib.comments` or `django_comments` in your `INSTALLED_APPS`, and uses those models.

**Comment by manihere** [comment]
thanks @vdboor **pip install django-threadedcomments==1.0b1** and a**dding django_comments in  INSTALLED_APPS** did it! :)
