### ISSUE TITLE
Can't reply the same content with same parent id

### ISSUE THREAD

**Issue by chunninc** [HonzaKral/django-threadedcomments#67]
Hi,
When I try to reply two commands with same content to the same parent, the second command will overwrite the first one and thus cost some bugs. Is it possible to reply same content under a command parent? Thanks for your help.

**Comment by vdboor** [comment]
Could you retry this with the 1.0 release? Some issues were fixed regarding updating the model. The example app shows it works fine now.

**Comment by jaineshp** [comment]
It is not working. Please help. Thanks!
