### ISSUE TITLE
RemovedInDjango19Warning

### ISSUE THREAD

**Issue by jimlyndon** [HonzaKral/django-threadedcomments#71]
On the latest commit (f5094aa2bf8b656154f08e603c09c873dc22eb79), I'm seeing a lot of these:

```
RemovedInDjango19Warning: Model class django_comments.models.Comment doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
```

Anyone else already experiencing or already reported this?  I'll dig in but didn't want to dup work.  Thanks!

**Comment by vdboor** [comment]
I noticed this too, but I'm not sure yet where to fix. Is this really an issue with threadecommends, or with https://github.com/django/django-contrib-comments? I noticed this fix here, which is not yet released: https://github.com/django/django-contrib-comments/commit/45347d0ae86f7e025197597f41e6d8d078ac8f2d

**Comment by jimlyndon** [comment]
I believe you are correct.  I've specified a recent threaded comment as it
points to the latest django comments release, where the problem seems to
have been resolved.
