### ISSUE TITLE
'django-threadedcomments version 1.0.1' don't support django 1.9

### ISSUE THREAD

**Issue by extremewaysback** [HonzaKral/django-threadedcomments#75]
When I push the project to heroku and get the following error. It seem that threadedcomments version 1.0.1 don't support django 1.9?

requirements.py:
Django == 1.9
gunicorn==19.3.0
whitenoise==2.0.4
psycopg2==2.6.1
reportlab==3.2.0
django-contrib-comments==1.6.1
threadedcomments==1.0.1

remote: -----> Using set buildpack heroku/python
remote: -----> Python app detected
remote: -----> Installing dependencies with pip
remote:        Collecting django-contrib-comments==1.6.1 (from -r requirements.txt (line 6))
remote:        Downloading django_contrib_comments-1.6.1-py2.py3-none-any.whl (51kB)
remote:        Collecting threadedcomments==1.0.1 (from -r requirements.txt (line 7))
remote:   Could not find a version that satisfies the requirement threadedcomments==1.0.1 (from -r requirements.txt (line 7)) (from versions: 0.1, 0.1.1, 0.2, 0.2.1, 0.3, 0.3.1, 0.4, 0.5)
remote: No matching distribution found for threadedcomments==1.0.1 (from -r requirements.txt (line 7))
remote: 
remote: 
remote:  !     Push rejected, failed to compile Python app

**Comment by rinti** [comment]
You are trying to install `threadedcomments==1.0.1` instead of `django-threadedcomments==1.0.1`.

**Comment by extremewaysback** [comment]
@rinti Thanks!
