### ISSUE TITLE
Unexpected keyword argument 'site_id' with get_comment_create_data

### ISSUE THREAD

**Issue by adrysn** [HonzaKral/django-threadedcomments#85]
Recent update of `django-contrib-comments` added `site_id` keyword argument to `get_comment_create_data`(https://github.com/django/django-contrib-comments/commit/1ab69cb122418c973e27210558d11bb3fba921f6).

`django-threadedcomments`'s `get_comment_create_data` may be changed to:

```
def get_comment_create_data(self, **kwargs):
    d = super(ThreadedCommentForm, self).get_comment_create_data(**kwargs)
    ...
```

**Comment by vdboor** [comment]
Fixed in f0fd6e3d4136db2c67a46baa0a11b66c02f26bf4! Thanks for reporting
