### ISSUE TITLE
Cannot run the example

### ISSUE THREAD

**Issue by icruces** [HonzaKral/django-threadedcomments#86]
Hi,

I have been trying to run the example but I cannot make it work. I am using Django 1.10.5 and when I try to access to the home page I get:

`no such table: core_message`

I have installed django-contrib-comments and run the migrations.

I can access to the admin page though, but the user/password: admin/admin doesn't work either.

Thanks.

**Comment by rodolphopivetta** [comment]
```bash
# on manage.py path
$ python manage.py makemigrations core
$ python manage.py migrate
$ python manage.py runserver
```

**Comment by lin344902118** [comment]
add a python-package named migrations and then run command makemigrations,migrate to create to create the table

**Comment by vdboor** [comment]
Thanks, I've fixed the example app!
