### ISSUE TITLE
Custom form

### ISSUE THREAD

**Issue by rodolphopivetta** [HonzaKral/django-threadedcomments#87]
I just want to add or remove some fields from default threadedcomments form.

What's the best way to override the form without have to modify templatetags?

**Comment by vdboor** [comment]
The django comments app provides this infrastructure. You can assign a different `COMMENTS_APP`, which provides the `get_model()` and `get_form()` logic (that then reuses the `threadedcomments/__init__.py` logic where possible.

An alternative is using https://github.com/django-fluent/django-fluent-comments which has this feature built-in. This app is build on top of the django comments / threaded comments so consider it icing the cake ;-)
