### ISSUE TITLE
Incompatible to Django 2.0

### ISSUE THREAD

**Issue by lmr2391** [HonzaKral/django-threadedcomments#93]
In Django 2.0 foreign key relations must have the parameter `on_delete` set: https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0
This is not the case for the parent field of the `ThreadedComment` model. To reflect the behaviour in Django 1.11, it would have to set to `models.CASCADE`

**Comment by vdboor** [comment]
Thanks! this is now merged.
