### ISSUE TITLE
New release tag? So Django 2.0 support is on PyPI

### ISSUE THREAD

**Issue by hangtwenty** [HonzaKral/django-threadedcomments#99]
Hey there, I saw  #93 adding support for Django 2.0 🎆 

Is it feasible to do a new tag/release so I don't have to depend on `master` directly? If there is something i can do to help make that possible, let me know 😄

**Comment by vdboor** [comment]
Thanks for the reminder! I've uploaded v1.2

**Comment by hangtwenty** [comment]
🙏

**Comment by eriktelepovsky** [comment]
Hi. Do you plan to release latest commits into pypi pls?
